---
_extends: gh-labels

repository:
  name: ocis-charts
  description: ":chart_with_upwards_trend: Helm Charts for ownCloud's OCIS"
  homepage: https://owncloud.dev/ocis/deployment/kubernetes/
  topics: helm, kubernetes, ocis, cloud-native, containers, devops

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: OCIS-Fastlane
    color: "#deadbf"
    description: Planned outside of the sprint

teams:
  - name: ci
    permission: admin
  - name: employees
    permission: push

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/drone/pr
      enforce_admins: null
      restrictions:
        apps: []
        users:
          - dependabot
        teams:
          - ci
          - employees
  - name: stable-5
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/drone/pr
      enforce_admins: null
      restrictions:
        apps: []
        users:
          - dependabot
        teams:
          - ci
          - employees
