---
ingress:
  enabled: true
  ingressClassName: some-ingress
  annotations:
    kubernetes.io/ingress.class: some-ingress
    kubernetes.io/tls-acme: "true"
  labels:
    label1: lorem
    label2: ipsum

  tls:
    - secretName: chart-example-tls
      hosts:
        - ocis.owncloud.test

externalDomain: ocis.owncloud.test

backup:
  configMapLabels:
    backup.test/include: "true"
    backup.test/configmap: "test"
  secretLabels:
    backup.test/include: "true"
    backup.test/secret: "test"
  pvcLabels:
    backup.test/include: "true"
    backup.test/pvc: "test"

image:
  pullSecrets:
    - name: some-pull-secret
nodeSelector:
  kubernetes.io/arch: "amd64"
hostAliases:
  - ip: "192.168.4.2"
    hostnames:
      - "example.kube.owncloud.test"
priorityClassName: ocis-middle-priority
jobPriorityClassName: ocis-job-middle-priority
features:
  emailNotifications:
    enabled: true
  appsIntegration:
    enabled: true
    wopiIntegration:
      wopiServerURI: https://wopiserver.owncloud.test
      officeSuites:
        - name: Collabora
          enabled: true
          uri: https://collabora.owncloud.test
          iconURI: https://collabora.owncloud.test/favicon.ico
          insecure: false
          ingress:
            enabled: true
            domain: collabora-wopi.owncloud.test
            ingressClassName: some-ingress
            annotations:
              kubernetes.io/ingress.class: some-ingress
              kubernetes.io/tls-acme: "true"
            labels:
              label1: lorem
              label2: ipsum
            tls:
              - secretName: chart-example-tls
                hosts:
                  - collabora-wopi.owncloud.test
        - name: OnlyOffice
          enabled: true
          uri: https://onlyoffice.owncloud.test
          iconURI: https://onlyoffice.owncloud.test/web-apps/apps/documenteditor/main/resources/img/favicon.ico
          insecure: false
          ingress:
            enabled: true
            domain: onlyoffice-wopi.owncloud.test
            ingressClassName: some-ingress
            annotations:
              kubernetes.io/ingress.class: some-ingress
              kubernetes.io/tls-acme: "true"
            labels:
              label1: lorem
              label2: ipsum
            tls:
              - secretName: chart-example-tls
                hosts:
                  - onlyoffice-wopi.owncloud.test
    mimetypes:
      - mime_type: application/vnd.oasis.opendocument.text
        extension: odt
        name: OpenDocument
        description: OpenDocument text document
        icon: ""
        default_app: ""
        allow_creation: true
  virusscan:
    enabled: true
  policies:
    enabled: true

extraLabels:
  extra1: lorem
  extra2: ipsum

podDisruptionBudget:
  maxUnavailable: 1

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

services:
  postprocessing:
    jobResources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  storagesystem:
    persistence:
      enabled: true
      storageClassName: default-storage
      accessModes:
        - ReadWriteMany
      size: 5Gi
      annotations:
        anno-1: test
      finalizers:
        - kubernetes.io/pvc-protection
      selectorLabels:
        selector1: foobar

  storageusers:
    storageBackend:
      driver: ocis
    persistence:
      enabled: true
      storageClassName: default-storage
      accessModes:
        - ReadWriteMany
      size: 50Gi
      annotations:
        anno-1: test
      finalizers:
        - kubernetes.io/pvc-protection
      selectorLabels: {}
    jobResources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    maintenance:
      cleanUpExpiredUploads:
        enabled: true
      purgeExpiredTrashBinItems:
        enabled: true
      restartPostprocessing:
        enabled: true

  thumbnails:
    persistence:
      enabled: true
      storageClassName: default-storage
      accessModes:
        - ReadWriteMany
      size: 10Gi
      annotations:
        anno-1: test
      finalizers: []
      selectorLabels:
        selector1: foobar
    jobResources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    jobNodeSelector:
      kubernetes.io/arch: "arm64"
    maintenance:
      cleanUpOldThumbnails:
        enabled: true

secretRefs:
  notificationsSmtpSecretRef: "smtp-secret"
